name: "dark overlord of data"
description: "if it's not dark, it's not data"

disqus: d16a
source: ./www
destination: ./public
port: 53610
url: http://darkoverlordofdata.com

paginate: 5
paginate_path: "list/page:num"

markdown: rdiscount
permalink: pretty
pygments: true

plugins:
  - hugin-asset-bundler
  - hugin-tag-cloud

tag_page_layout: tag_page
tag_page_dir: tag

asset_bundler:
  compress:
    js: true
    css: true
  base_path: /assets/
  server_url: //cdn.darkoverlordofdata.com/
  remove_bundled: false
  dev: false
  markup_templates:
    js: "<script type='text/javascript' src='{{url}}'></script>\n"
    css: "<link rel='stylesheet' type='text/css' href='{{url}}' />\n"